name: CI CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run tests + build
        run: mvn clean verify

      - name: Build image docker
        run: docker build -t gymprogress:0.0.1 .

      - name: Login to docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Tag docker
        run: docker tag gymprogress:0.0.1 ${{secrets.DOCKER_USERNAME}}/gymprogress:0.0.1

      - name: Push to docker
        run: docker push ${{secrets.DOCKER_USERNAME}}/gymprogress:0.0.1
